import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/global/Navbar";
import localFont from "next/font/local";

const ChalkStick = localFont({
  src: '../../public/fonts/ChalkStick.ttf', // Adjust path as needed
  variable: '--chalk-stick-font',
  display: 'swap',
});

const CreamyChalk = localFont({
  src: '../../public/fonts/CreamyChalk.ttf', // Adjust path as needed
  variable: '--creamy-chalk-font',
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${ChalkStick.variable} ${CreamyChalk.variable} font-sans`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
